/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class Metadata extends SpeakeasyBase {}

export class Element extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "element_id" })
    elementId: string;

    @SpeakeasyMetadata()
    @Expose({ name: "metadata" })
    @Type(() => Metadata)
    metadata: Metadata;

    @SpeakeasyMetadata()
    @Expose({ name: "text" })
    text: string;

    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type: string;
}
