/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type Loc = string | number;

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

/** @internal */
export namespace Loc$ {
    export const inboundSchema: z.ZodType<Loc, z.ZodTypeDef, unknown> = z.union([
        z.string(),
        z.number().int(),
    ]);

    export type Outbound = string | number;
    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Loc> = z.union([
        z.string(),
        z.number().int(),
    ]);
}

/** @internal */
export namespace ValidationError$ {
    export const inboundSchema: z.ZodType<ValidationError, z.ZodTypeDef, unknown> = z.object({
        loc: z.array(z.union([z.string(), z.number().int()])),
        msg: z.string(),
        type: z.string(),
    });

    export type Outbound = {
        loc: Array<string | number>;
        msg: string;
        type: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ValidationError> = z.object({
        loc: z.array(z.union([z.string(), z.number().int()])),
        msg: z.string(),
        type: z.string(),
    });
}
