workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: https://api.unstructured.io/general/openapi.json
targets:
    unstructed-typescript:
        target: typescript
        source: my-source
