workflowVersion: 1.0.0
sources:
    my-source:
        inputs:
            - location: https://api.unstructured.io/general/openapi.json
targets:
    unstructed-typescript:
        target: typescript
        source: my-source
        # publish:
        #     npm:
        #         token: $NPM_TOKEN
