name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  merge_group:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: npm
          cache-dependency-path: ./package.json
          node-version: 18
      - name: Install dependencies
        run: make install
      - name: Build dependencies
        run: make build
      - name: Run linter
        run: make check
      - name: Run unit tests
        run: make test-unit
    

  test_integration:
    runs-on: ubuntu-latest
    services:
      unstructured-api:
        image: quay.io/unstructured-io/unstructured-api:latest
        ports:
          - 8000:8000
    steps:
    - uses: actions/checkout@v4
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        cache: npm
        cache-dependency-path: ./package.json
        node-version: 18
    - name: Install dependencies
      run: make install
    - name: Build dependencies
      run: make build
    - name: Run integration tests
      run: make test-integration
