name: Publish
"on":
  push:
    branches:
      - main
    paths:
      - RELEASES.md
jobs:
  publish:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-publish.yaml@v14
    with:
      create_release: true
      publish_typescript: true
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
      npm_token: ${{ secrets.NPM_TOKEN }}
